---
db:
  driver: dbi:Pg:planetmultimedia
  user: harvester
  password: planetmultimedia
settings:
  size limit: 1024000
  timeout: 90
  templates: templates
  output: /var/www/planet.multimedia.cx/public
collections:
  blogs:
  - http://blog.flameeyes.eu/category/multimedia.atom
  - "http://codecs.multimedia.cx/?feed=rss2"
  - http://multimedia.cx/eggs/feed/
  # very old blog for Alex Converse
  - http://blog.case.edu/ajc30/index.rdf
  # new blog for Alex Converse
  - http://spectralhole.blogspot.com/feeds/posts/default
  - http://hardwarebug.org/feed/
  - http://www.jbkempf.com/blog/feed/rss2
  - http://www.jpsaman.org/aggregator/rss
  - http://feeds.feedburner.com/feepk
  - http://blog.l0cal.com/feed/
  - http://blogs.gentoo.org/lu_zero/category/multimedia/feed/
  - http://blog.gingertech.net/feed/
  - http://blogs.gnome.org/edwardrv/feed/
  - http://www.remlab.net/feed.xml
  microblogs:
  # flameeyes
  - http://twitter.com/statuses/user_timeline/14383295.rss
  # videolan
  - http://twitter.com/statuses/user_timeline/88776463.rss
  # silviapfeiffer
  - http://twitter.com/statuses/user_timeline/7678792.rss
