---
db:
  driver: dbi:Pg:harvester:localhost
  user: astro
  password: ***
settings:
  size limit: 102400
  timeout: 90
  templates: templates
  output: html
jabber:
  jid: astrobot@spaceboyz.net/harvester
  password: ***
  interval: 120
collections:
  ticker:
  - http://www.c3d2.de/news-atom.xml
  - http://planet.c3bi.de/rss20.xml
  - http://www.blacksec.org/index2.php?option=com_rss&feed=RSS0.91&no_html=1
  - http://planet.entropia.de/rss.rdf
  - http://bruteforce.blogg.de/rss.xml
  - http://asocio.no-ip.com/unter-schwarzer-flagge/?feed=rss2
  links:
  - http://del.icio.us/rss/fukami
  - http://del.icio.us/rss/astro1138
  - http://del.icio.us/rss/toidinamai
  - http://del.icio.us/rss/r0b0
  - http://del.icio.us/rss/pentabarf
  - http://del.icio.us/rss/tigion
  - http://del.icio.us/rss/turbo24prg
  - http://del.icio.us/rss/mechko
  - http://del.icio.us/rss/DerTobendeGummihammer
  - http://del.icio.us/rss/Alien8
  - http://del.icio.us/rss/boelthorn
  - http://del.icio.us/rss/rabuju
  - http://del.icio.us/rss/cosmoFlash
  - http://del.icio.us/rss/Shnifti
  - http://del.icio.us/rss/stepardo
  - http://blog.tigion.de/feed/
  blogs:
  - http://astroblog.spaceboyz.net/rss.rb
  - http://blog.tigion.de/feed/atom/
  - http://fukami.vakuum.net/feed/
  - http://blog.daemonized.de/feed/
  - http://www.psycast.de/blog/rss.php?ver=2
  - http://www.kuarepoti-dju.net/wp-rss2.php
  - http://spaceboyz.net/~cosmo/updates.rss
  - http://89.238.64.223/semaphor/semaphor.php?item=blogRss
  - http://www.marvinnet.org/?feed=rss2
  - http://d-ventures.heartofgold.de/?feed=rss2
  - http://jelena.blogsome.com/feed/rdf/
  - http://equiblog.diac24.net/$rss:full4
  - http://matthias.bsd-crew.de/blog/?feed=atom
  - http://cthulhu.c3d2.de/~toidinamai/blog.py/index.atom
  - http://www.stecklina.info/blog/atom
  - "http://api.flickr.com/services/feeds/photos_public.gne?id=73915810@N00&format=atom"
  - http://bsd-crew.de/~riot/rss.xml
  - http://www.haltetdenbeat.de/feed/
  - http://vserver152.masterssystems.com/blog/feed/
  - http://stepardos.blogspot.com/feeds/posts/default
