---
db:
  driver: dbi:Mysql:harvester:localhost
  user: root
  password: tototo
settings:
  size limit: 102400
  timeout: 90
  templates: templates
  output: html
jabber:
  jid: bot@cepheide.org/harvester
  password: 
  interval: 120
collections:
  ticker:
  projects:
  - http://hackerspace.net/vhsroom.atom
  links:
  - http://del.icio.us/rss/hackerspace
  blogs:
  - http://hackerspace.net/blog.atom
  - http://vancouver.hackspace.ca/?q=node/4
  photos:
