---
db:
  driver: dbi:Pg:planetmultimedia
  user: harvester
  password: planetmultimedia
settings:
  size limit: 102400
  timeout: 90
  templates: templates
  output: /var/www/planet.multimedia.cx/public
collections:
  blogs:
  - http://blog.flameeyes.eu/category/multimedia.atom
  - "http://codecs.multimedia.cx/?feed=rss2"
  - http://multimedia.cx/eggs/feed/
  - http://blog.case.edu/ajc30/index.rdf
  - http://hardwarebug.org/feed/
  - http://www.jbkempf.com/blog/feed/rss2
  - http://www.jpsaman.org/aggregator/rss
  microblogs:
  - http://twitter.com/statuses/user_timeline/14383295.rss
