---
db:
  driver: dbi:Mysql:harvester:localhost
  user: root
  password: tototo
settings:
  size limit: 102400
  timeout: 90
  templates: templates_hsnet
  output: html
jabber:
  jid: bot@cepheide.org/harvester
  password: 
  interval: 120
collections:
  ticker:
  - http://hackerspaces.org/w/index.php?title=Special:Recentchanges&feed=atom
  - http://hackerspace.net/vhsroom.atom
  links:
  - http://feeds.delicious.com/v2/rss/tag/hackerspace?count=15
  - http://feeds.delicious.com/v2/rss/tag/hackerspaces?count=15  
  - http://feeds.delicious.com/v2/rss/tag/hacklab?count=15
  blogs:
  - http://hackerspace.net/blog.atom
  - http://hacklab.planetax.org.ar/feed.php
  - http://blog.open4free.org/?feed=rss2
  - http://lab.netculture.at/kontakt/wien/feed/
  - http://lab.netculture.at/feed/
  - http://www.metalab.at/feeds/events
  - https://realraum.at/wiki/feed.php
  - http://lab.ccc-linz.at/feed.php
  - http://www.hamiltonhackerspace.com/?feed=atom
  - http://vancouver.hackspace.ca/?q=rss.xml
  - http://hacklab.to/feed/
  - http://www.fazan.org/?q=node/feed
  - http://www.tmplab.org/feed/atom/
  - http://www.port20.org/feed/atom/
  - https://www.c3d2.de/news-atom.xml
  - http://www.netzladen.org/export/termine_rss
  - http://www.cccmz.de/?feed=atom
  - https://wiki.chaos-paderborn.de/feed.php
  - http://sublab.subsignal.org/wikka.php?wakka=space/recentchanges.xml
  - http://koeln.ccc.de/backend/updates.rdf
  - http://www.chaos-darmstadt.de/b/?feed=atom
  - https://www.hamburg.ccc.de/feed/atom
  - http://www.das-labor.org/blog/index.php/feed/atom/
  - http://nextlab.hu/rss.xml
  - http://poetry.freaknet.org/index.php?title=Speciale:UltimeModifiche&feed=atom
  - http://gobelab.hacklabs.org/?feed=atom
  - http://www.autistici.org/underscore/feed.php
  - http://altctrlsupr.net/feed/
  - http://www.mallory.lu/wiki/index.php?title=Special:RecentChanges&feed=atom
  - http://blog.kaotik.org/feed/atom/
  - http://www.kiberpipa.org/backend.php
  - http://www.ductape.co.za/feed/
  - http://riereta.net/drupal/rss.xml
  - http://null-lab.hacklabs.org/mediaw/index.php?title=Especial:Recentchanges&feed=atom
  - http://dock48.ch/web/feed.php?type=all
  - http://hacdc.org/feed/
  - http://thehacktory.org/rss.xml
  - http://www.willoughbybaltic.com/home/index.php?format=feed&type=atom
  - http://dc401.org/site/atom.xml
  - http://www.nycresistor.com/feed/atom/
  - http://www.hackerbotlabs.com/?feed=atom
  - http://www.dc206.org/?feed=atom
  - http://www.hackerfoundation.org/rss.xml
  - http://mhs.hackerdemia.com/feed.php
  - http://machineproject.com/feed/
  - http://tktech.org/blog/feed/atom/
  - https://www.noisebridge.net/index.php?title=Special:Recentchanges&feed=atom
  - http://feeds.feedburner.com/eyebeam/news
  - http://sindominio.net/metabolik/weblog/wp-atom.php
  - http://www.hacklabs.org/?q=en/node/feed
  - http://www.servesita.org/hackarena/blog/feed/
  - http://asturlab.xwiki.com/xwiki/bin/view/Blog/BlogRss?xpage=rdf
  - http://blog.kaslab.net/?feed=rss2
  - https://wiki.boum.org/CyberForat/WebRss
  - http://www.freaknet.org/news/rss.php
  - http://entkapselt.de/index.php?/feeds/atom10.xml
  - http://logbuch.c-base.org/feed/
  - https://blog.feint.org/index.php/feed/
  - http://www.sok.hr/joomla_cisco/index2.php?option=com_rss&feed=rss20.xml&no_html=1
  - http://vnsecurity.net/news/RSS
  - http://www.cciz.de/wiki/feed.php
  - https://berlin.ccc.de/mediawiki/index.php?title=Spezial:Letzte_%C3%84nderungen&feed=atom
  - http://wiki.attraktor.org/index.php?title=Spezial:Letzte_Änderungen&feed=atom
  - http://entropia.de/wiki/index.php?title=Spezial:Recentchanges&feed=atom
  - http://planet.entropia.de/rss.rdf
  - http://ccchb.de/w/index.php?title=Spezial:Letzte_Änderungen&feed=atom
  - http://145.be/voidpointer/feed.php
  photos:
  - http://api.flickr.com/services/feeds/photos_public.gne?tags=hackerspace&lang=en-us&format=rss_200
  - http://api.flickr.com/services/feeds/photos_public.gne?tags=hackerspaces&lang=en-us&format=rss_200
  - http://api.flickr.com/services/feeds/photos_public.gne?tags=hacklab&lang=en-us&format=rss_200
